#!/bin/ash
# Called to start IPsec

# By failure exit with "1"!
set -e

# Setup NAT forwarding if not already set, see '$ iptables -t nat -L' and
# https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling

iptables --table nat --check POSTROUTING --jump MASQUERADE || {
  iptables --table nat --append POSTROUTING --jump MASQUERADE
}

# When starting container for the first time we need to generate certificates.
# They can be regenerated on demand by using setup scripts directly.
if [ ! -f /.initialized ]; then
    setup host $VPN_HOST
    setup user $VPN_USER $VPN_PASSWORD
    touch /.initialized
fi

# Start IPsec
ipsec start --nofork
