#!/bin/ash
# Manage VPN secrets

case "$1" in
  export)
    echo "Exporting existing set of secrets to mounted container volume ..."
    cd /etc/ipsec.d
    cp --force cacerts/* /mnt/
    cp --force certs/* /mnt/
    cp --force private/* /mnt/
    echo "Done!"
    ;;
  import)
    # Assign variables
    user=$2
    password=$3

    echo "Importing existing set of secrets from mounted container volume ..."
    cd /mnt
    cp --force caCert.pem /etc/ipsec.d/cacerts/
    cp --force serverCert.pem *Cert.pem /etc/ipsec.d/certs/
    cp --force caKey.pem serverKey.pem *Key.pem /etc/ipsec.d/private/

    echo "Setting the server key"
    echo ": RSA serverKey.pem" > /etc/ipsec.secrets
    echo "Setting the XAUTH password"
    echo "${user} : XAUTH \"${password}\"" >> /etc/ipsec.secrets
    echo "Done, will restart IPsec and container!"

    # Restart IPsec, some how '$ ipsec rereadall' does not do the job,
    # let's go aggressive
    ipsec restart
    ;;
esac
